"""create_discovery_jobs_table

Revision ID: 15e76d6d3e79
Revises: 6e0de6c4c08e
Create Date: 2026-07-28 09:36:31.885167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15e76d6d3e79'
down_revision: Union[str, Sequence[str], None] = '6e0de6c4c08e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovery_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('profile', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_hosts', sa.Integer(), nullable=False),
    sa.Column('processed_hosts', sa.Integer(), nullable=False),
    sa.Column('current_host', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discovery_jobs')
    # ### end Alembic commands ###
