"""create scan_ports table

Revision ID: 729747285822
Revises: f0259a360ace
Create Date: 2026-07-27 09:17:16.660347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '729747285822'
down_revision: Union[str, Sequence[str], None] = 'f0259a360ace'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_ports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=10), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('service', sa.String(length=100), nullable=True),
    sa.Column('product', sa.String(length=150), nullable=True),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('extra_info', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scan_ports')
    # ### end Alembic commands ###
