"""create fingerprints table

Revision ID: c3524249421b
Revises: 15e76d6d3e79
Create Date: 2026-07-29 09:50:18.945946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3524249421b'
down_revision: Union[str, Sequence[str], None] = '15e76d6d3e79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fingerprints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_port_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('vendor', sa.String(length=100), nullable=True),
    sa.Column('product', sa.String(length=150), nullable=True),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('cpe', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scan_port_id'], ['scan_ports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fingerprints')
    # ### end Alembic commands ###
