"""create_vulnerabilities_table

Revision ID: e51ca44e9adb
Revises: bc5835fa9669
Create Date: 2026-07-27 13:33:59.911479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e51ca44e9adb'
down_revision: Union[str, Sequence[str], None] = 'bc5835fa9669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vulnerabilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_port_id', sa.UUID(), nullable=False),
    sa.Column('cve', sa.String(length=40), nullable=False),
    sa.Column('cvss', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scan_port_id'], ['scan_ports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vulnerabilities_cve'), 'vulnerabilities', ['cve'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_scan_port_id'), 'vulnerabilities', ['scan_port_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vulnerabilities_scan_port_id'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_cve'), table_name='vulnerabilities')
    op.drop_table('vulnerabilities')
    # ### end Alembic commands ###
