"""add cpe to scan_ports

Revision ID: ea69213c50d3
Revises: 729747285822
Create Date: 2026-07-27 12:04:14.084763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea69213c50d3'
down_revision: Union[str, Sequence[str], None] = '729747285822'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_ports', sa.Column('cpe', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_ports', 'cpe')
    # ### end Alembic commands ###
